server.port=8080
spring.application.name=barber-shop-api

# Configurações do servidor Spring Web
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Configuração de logging
logging.level.root=INFO
logging.level.br.com.barbershop=DEBUG
